- hosts: all
  vars_files:
    - "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
  tasks:
  - name: Install package
    package:
            name: "{{ package }}"
            state: present

  - name: copy webpage
    template:
        dest: "{{ doc_root }}"
        src: "/root/web.html"

  - name: start service
    service:
         name: "{{ service }}"
         state: started
